### ISSUE TITLE
Add vscodeHarpoon.harpoon file to .vscode

### ISSUE THREAD

**Issue by Dandarprox** [tobias-z/vscode-harpoon#12]
**Is your feature request related to a problem? Please describe.**
It is kind of a problem, when you work with git, usually the .gitignore file includes the .vscode folder, so I would consider this folder a better place to locate the vscodeHarpoon.harpoon since by default it will be ignored.

**Describe the solution you'd like**
Just place the vscodeHarpoon.harpoon file in the .vscode folder

**Describe alternatives you've considered**
Not sure if it is possible, but the file could be stored outside the project

**Additional context**
.

**Comment by tobias-z** [comment]
Your probably right, that would most likely be a better place to store it. I was hoping it wouldn't be caught by git since it is beeing removed, but it looks like that doesn't happen some times...

I think storing it somewhere else would be ideal perhaps in ~/.vscode/vscodeHarpoon.harpoon

**Comment by tobias-z** [comment]
I was able to place it into ~/.vscode/vscodeHarpoon.harpoon
As far as i can tell it still works on all systems
