### ISSUE TITLE
Duplicates in edit list

### ISSUE THREAD

**Issue by Dandarprox** [tobias-z/vscode-harpoon#13]
**Describe the bug**
I accidentally added to the editor list the same file multiple times where I was expecting it to have a single instance of the file in the editor list

**To Reproduce**
1. Run command Harpoon add editor in the file X
2. Run the same command in the same file X
3. Open the editor quick pick and see two copies of the same file X

**Expected behavior**
To have list with unique elements, even if the files are added several times, it should be only a single instance.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by tobias-z** [comment]
This has been implemented and will be released in the next release
