### ISSUE TITLE
If file already open in editor, switch to that instead of opening new editor

### ISSUE THREAD

**Issue by MartinBernstorff** [tobias-z/vscode-harpoon#16]
**Is your feature request related to a problem? Please describe.**
Would love to utilise this for split view - have my harpoon editors open in each split, and use the keyboard shortcuts to switch between them.

**Describe the solution you'd like**
Press harpoon shortcut -> 
    If file is not open, open it in current editor
    If file is open, switch to that editor

**Comment by tobias-z** [comment]
Hello there - thank you for taking an interest in the extension!
I'm very sorry for the long wait as i have been busy with my studies :book: 
Your request should work now when you update the extension. 
However, you will have to change a property in the settings.json file.

```json
{
  "workbench.editor.revealIfOpen": true
}
```
