### ISSUE TITLE
Requesting dedicated/specific "addEditor[1-9]" in addition to the generalized "addEditor" commands

### ISSUE THREAD

**Issue by instance-id** [tobias-z/vscode-harpoon#17]
Hello,
I would like to request an "addEditor[1-9]" command(s), in addition to the general "addEditor". 

An example of this in action can be seen in the IdeaVim version of this plugin: [HarpoonIJ](https://plugins.jetbrains.com/plugin/20782-harpoonij). It has this functionality and it is great to quickly swap out individual marks. The actual functionality being that it adds the current editor directly to the editor list at the specified index[1-9] as opposed to appending it to the next available index.

Ex. excerpt from my current .ideavimrc file.
```vim
" --| Harpoon -------------------------
nmap <leader><C-j> :action SetHarpoon1<cr>
nmap <leader><C-k> :action SetHarpoon2<cr>
nmap <leader><C-l> :action SetHarpoon3<cr>
nmap <leader><C-;> :action SetHarpoon4<cr>

nmap <C-j> :action GotoHarpoon1<cr>
nmap <C-k> :action GotoHarpoon2<cr>
nmap <C-l> :action GotoHarpoon3<cr>
nmap <C-;> :action GotoHarpoon4<cr>

nmap <leader><C-e> :action ShowHarpoon<cr>
nmap <leader><C-a> :action AddToHarpoon<cr>
``` 

Mockup of VSCode settings.json with this feature.

```jsonc
    ...
    // --| Harpoon ---------------
    // --| Edit Marks -------
    { "before": ["<leader>", "<C-e>"], "commands": ["vscode-harpoon.editEditors"] },

    // --| Add---------------
    { "before": ["<leader>", "<C-j>"], "commands": ["vscode-harpoon.addEditor1"] },
    { "before": ["<leader>", "<C-k>"], "commands": ["vscode-harpoon.addEditor2"] },
    { "before": ["<leader>", "<C-l>"], "commands": ["vscode-harpoon.addEditor3"] },
    { "before": ["<leader>", "<C-;>"], "commands": ["vscode-harpoon.addEditor4"] },

    // --| Go-To-------------
    { "before": ["<C-j>"], "commands": ["vscode-harpoon.gotoEditor1"] },
    { "before": ["<C-k>"], "commands": ["vscode-harpoon.gotoEditor2"] },
    { "before": ["<C-l>"], "commands": ["vscode-harpoon.gotoEditor3"] },
    { "before": ["<C-;>"], "commands": ["vscode-harpoon.gotoEditor4"] },
    ...
```

Thank you for your time and consideration,
-id

**Comment by tobias-z** [comment]
Hello there,
Thank you for having an interest in the project :smile: 
I have implemented your request, and you should be able to update the extension with the new feature.

**Comment by instance-id** [comment]
This is great news. I definitely appreciate it. :+1:
