### ISSUE TITLE
Q: remap "<C-n>" to focus next search result in "editorQuickPick"

### ISSUE THREAD

**Issue by gandastik** [tobias-z/vscode-harpoon#19]
what is the command (if there is any) and the "when" condition that I can use in the vs-code settings.js

for more information:
![setting](https://media.discordapp.net/attachments/1014398974649708624/1087050713558945842/image.png)

ps. ty for this lovely extension ❤️

**Comment by tobias-z** [comment]
Hello gandastik
I believe what you want is to set a shortcut for `workbench.action.quickOpenNavigateNext` in your vscode keyboard shortcuts.
Something like

```json
{
    "key": "ctrl+n",
    "command": "workbench.action.quickOpenNavigateNext"
}
```
additionally you can also set the `workbench.action.quickOpenNavigatePrevious` option. In that case you prob also want to change the shortcut for `workbench.action.quickOpen`

If i'm incorrect please feel free to reopen the issue
