### ISSUE TITLE
Edit List Disappears

### ISSUE THREAD

**Issue by dezren39** [tobias-z/vscode-harpoon#24]
**Describe the bug**

Sometimes my edit list appears to disappear. To be fair, this may be user error on my part but I'm not sure where. When it's working and I have a lot of stuff open it all seems to work fine, but when I'm just getting setup, sometimes my list seems to disappear. Maybe if I didn't compulsively hit ctrl+w as often, but I didn't know that would prevent the file from just being reopened if that is the case.

**To Reproduce**

1. Alt+A Add item.
1. Close file or redirect to another file (tried both.)
1. Alt+E Edit editors (item is there.)
1. Save/Close Without Changes (tried both.)
1. Alt+1 GoTo Editor (nothing happens.)
1. Alt+E Edit editors (empty file.)

**Expected behavior**

1. Alt+A Add item.
1. Close file or redirect to another file.
1. Alt+E Edit editors (item is there.)
1. Save/Close Without Changes.
1. Alt+1 GoTo Editor: Jump to item added earlier.
1. Alt+E Edit editors (item is still there.)

**Desktop (please complete the following information):**

 - OS: Windows

**Additional context**

Sometimes it doesn't disappear? May be linked to having a completely empty workspace with no documents open? I tried with and without using a code workspace. My code directory is located in a drive separate from my user profile folder where my vs code extension settings, etc are. Should my local list appear in my workspace or is it supposed to always be in c:\users\<user> somewhere related to the extension location?

**Comment by adam2am** [comment]
Hello there, I'm facing the same issue. Could you please share how you solved it?
