### ISSUE TITLE
Support for Live Share

### ISSUE THREAD

**Issue by shellwhale** [tobias-z/vscode-harpoon#25]
Switching doesn't work for [Live Share](https://code.visualstudio.com/learn/collaboration/live-share)

**Comment by tobias-z** [comment]
What exactly is not working with it? Under which conditions does it not work?

When you say that it doesn't work, do you mean when you join someone else's workspace, and what would you expect it to do in their workspace?

**Comment by shellwhale** [comment]
Sorry for the lack of additional context. When joining someone else's workspace, first it doesn't seem possible to use vscode-harpoon commands such as `Add editor N` or `Go to editor N`. (even if I set the remote workspace as trusted).

I expected the behavior to simply remain the same as locally, except for global editors. To have the ability to `Add editor` for one of their remote files and then `Go to editor`.

I'm not familiar with the inner workings of vs-code harpoon. Is `Add editor` is "session based" and Add `global editor` is saving the editor "permanently"?

**Comment by tobias-z** [comment]
Hello there. Thank you for the extra context.
I have implemented a fix which should allow you to move around like you would expect during a live share session now.
Ones you update the extension all should be well.
