### ISSUE TITLE
The ability to edit how much of the path that gets displayed in the quick pick selection would be a great convenience in my opinion. currently when I am working with deeply nested files and folders I cannot see the actual file name I am trying to access from the quick pick since the selection bar is not wide enough to display the full path. Could it be set to relative to the current git repo even?

### ISSUE THREAD

**Issue by ProSweeper** [tobias-z/vscode-harpoon#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ProSweeper** [comment]
![image](https://github.com/tobias-z/vscode-harpoon/assets/97694200/c6a151d0-84ea-475d-b81d-961181781535)
Just for a frame of reference here is an image of the issue

**Comment by tobias-z** [comment]
Hey, sorry for the late response.
This was a bug in the implementation for windows, and has been fixed. It will be deployed in the next release.

**Comment by ProSweeper** [comment]
No worries, thanks for response! love the plug in btw
