### ISSUE TITLE
The ability to switch between next and previous buffer would be awesome

### ISSUE THREAD

**Issue by french0u0** [tobias-z/vscode-harpoon#29]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but a pure feature request.

**Describe the solution you'd like**
I think in theprimeagen's nvim plugin, you can have one command switch between buffers one and two very fast. The same command also switches back to the "current" buffer once you've switched to the "previous" buffer, so that you only need one command for example: <leader> "n" to switch between to buffers very fast.

**Describe alternatives you've considered**
For now I'm using ctrl-6 to do this since I use the vim plugin for vscode and this is the -switch between last buffer command- in vim

**Additional context**
/

**Comment by tobias-z** [comment]
I'm not familiar with this command. Are you saying that this is specifically for the editors 1 and 2, or more general that it switches back the previous editor you switched from using harpoon?

**Comment by rupture-ttv** [comment]
Just my 2 cents.  I think they mean 
> or more general that it switches back the previous editor you switched from using harpoon?

**Comment by french0u0** [comment]
Yeah that's what I mean. Sorry, it was a bit vague in my head when I was jotting it down. Should've put buffer x and buffer y instead of one and two. But yeah switching to the previous editor you switched from using harpoon is what I mean

**Comment by tobias-z** [comment]
Okay, I'll see what I can do. This sounds like a feature which would be nice to have

**Comment by tobias-z** [comment]
This has been implemented, and is being deployed as of now. You should be able to update the plugin and find the new command `VSCode Harpoon: Go to previous harpoon editor` which can be bound to anything using the command name: `vscode-harpoon.gotoPreviousHarpoonEditor`

(there is also a global version if wanted)
