### ISSUE TITLE
[:sparkles:] Feature: make a command to go to next like the previus one

### ISSUE THREAD

**Issue by TheElegantCoding** [tobias-z/vscode-harpoon#33]
make a command to go to next file, like the previous one

**Comment by tobias-z** [comment]
What would you expect the "go to next" to do? I feel like the "go to previous" one is already kind of doing both. It doesn't work exactly like ctrl+o in vim, instead it will just go back and fourth between editors when calling it multiple times.

**Comment by vansoest** [comment]
+1 for this feature.—missing next file, just to cycle in a specific direction. But you see it’s not constant, remapped your extension if I use vscode-vim: 
```
if exists('g:vscode')
	nnoremap <leader>hl <Cmd>lua require('vscode-neovim').action('vscode-harpoon.gotoPreviousGlobalHarpoonEditor')<CR>
else:
	nnoremap <leader>ha :lua require("harpoon.ui").nav_next()<cr>
	nnoremap <leader>hl :lua require("harpoon.ui").nav_prev()<cr>
endif
```

so why not implement it consistent?

**Comment by tobias-z** [comment]
As far as i can tell, the harpoon `nav_next` and `nav_prev` functions do a compleatly different thing than this `gotoPreviousHarpoonEditor` does. The vscode-harpoon one goes back and fourth between two files, whereas the harpoon ones just nav throught the list of items.
I don't mind the feature, but it doesn't really have anything to do with the current `gotoPreviousHarpoonEditor` function

**Comment by TheElegantCoding** [comment]
i understand but it will be a nice feature to add, so this way we have the next and previous functionality
